name: test_deployment_full_staking_node

on:
  push:
    branches:
      - main

jobs:
  run-lido-csm-staking-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: ./install-nimbus-nethermind.sh skip
      - name: Deploy a Lido CSM Staking node, consisting of EL CL VC and mevboost
        run: python3 ./deploy-nimbus-nethermind.py --skip_prompts="true" --network="HOLESKY" --install_config="Lido CSM Staking Node"
